# Generated by Django 3.0.5 on 2020-05-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('similar_user_id', models.IntegerField()),
            ],
        ),
        migrations.AddIndex(
            model_name='similaruser',
            index=models.Index(fields=['user_id'], name='collaborati_user_id_3e1e00_idx'),
        ),
    ]
