"""
Django settings for ChefItUp project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

import environ

# Get root of the project
import tweepy
from django.contrib import messages

from .spoonacular_utils.api import API

root = environ.Path(__file__) - 2

# Set casting, default value
#env = environ.Env(DEBUG=(bool, False))

# False if not in os.environ
#DEBUG = env('DEBUG')
DEBUG = True

# Reading .env file
#environ.Env.read_env()

SITE_ROOT = root()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = env('SECRET_KEY')
SECRET_KEY = '_p07e+w8=vy)x9mn*=84g4m&l98+@387pxvk^v(8of$3^_a7sw'
#SPOONACULAR_API_KEY = env('SPOONACULAR_API_KEY')
SPOONACULAR_API_KEY = os.environ.get('SPOONACULAR_API_KEY')
SPOONACULAR_API = API(SPOONACULAR_API_KEY)
ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'users.CustomUser'

# Forcing SSL Connection
SECURE_SSL_REDIRECT=False
SESSION_COOKIE_SECURE=False
CSRF_COOKIE_SECURE=False

# Application definition

INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ChefItUp.simple_recommendation',
    'webapp',
    'users.apps.UsersConfig',
    'crispy_forms',
    'django.contrib.sites',
    'coverage',
    'django_user_agents',
    'widget_tweaks',
    'collaborative_recommendation',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.twitter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = 'ChefItUp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ChefItUp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
# DATABASES = {
#     # read os.environ['DATABASE_URL'] and raises ImproperlyConfigured exception if not found
#     'default': env.db()
# }

import dj_database_url

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


fetchedRecipes = SPOONACULAR_API.get_random_recipes(number=20).json().get('recipes')
print('[Spoonacular API] Fetching Recipes...')

QUOTA_REACHED = False
RECIPELIST = []

if fetchedRecipes is not None:
    RECIPELIST = list(map(lambda recipe_dict: {
        'title': recipe_dict.get('title'),
        'vegan': recipe_dict.get('vegan'),
        'vegetarian': recipe_dict.get('vegetarian'),
        'gluten_free': recipe_dict.get('glutenFree'),
        'ketogenic': recipe_dict.get('ketogenic'),
        'dairy_free': recipe_dict.get('dairyFree'),
        'img': 'https://spoonacular.com/recipeImages/{}-556x370.jpg'.format(recipe_dict.get('id')),
        'id': recipe_dict.get('id'),
        'img': recipe_dict.get('image'),
        'ingredients': recipe_dict.get('ingredients'),
        'extendedIngredients': recipe_dict.get('extendedIngredients'),
    }, fetchedRecipes))
    
    # Removing Recipes without an Image (Spoonacular Bug)
    for recipe in RECIPELIST:
        if recipe.get('img') is None:
            RECIPELIST.remove(recipe)
else:
    QUOTA_REACHED = True

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

SITE_ID = 1

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = True

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

INGREDIENTS_DICT = {"Dairy": ["salted butter", "unsalted butter", "margarine", "egg", "skimmed milk", "whole milk", "semi-skimmed milk", "parmesan", "cheddar", "american cheese", "sour cream", "cream cheese", "mozzarella", "yogurt", "double cream", "single cream", "evaporated milk", "whipped cream", "half and half", "feta", "monterey jack cheese", "condensed milk", "cottage cheese", "ice cream", "swiss cheese", "velveeta", "frosting", "buttermilk", "ricotta", "goat cheese", "provolone", "blue cheese", "powdered milk", "colby cheese", "pepper jack", "italian cheese", "soft cheese", "gouda", "pepperjack cheese", "romano", "brie", "pizza cheese", "ghee", "creme fraiche", "cheese soup", "guyere", "pecorino cheese", "custard", "muenster", "queso fresco cheese", "hard cheese", "havarti cheese", "asiago", "mascarpone", "neufchatel", "halloumi", "paneer", "brick cheese", "camembert cheese", "goat milk", "garlic herb cheese", "edam cheese", "manchego", "fontina", "stilton cheese", "emmenthaler cheese", "red leicester cheese", "jarlsberg cheese", "bocconcini cheese", "farmer cheese", "creme de cassis", "wensleydale cheese", "longhorn cheese", "double gloucester cheese", "raclette cheese", "lancashire cheese", "cheshire cheese"],
                    "Vegetables": ["onion", "garlic", "tomato", "potato", "carrot", "bell pepper", "basil", "parsley", "broccoli", "sweetcorn", "spinach", "mushroom", "green beans", "ginger", "red chili pepper", "green chili pepper", "celery", "rosemary", "salad greens", "red onion", "cucumber", "sweet potato", "pickle", "avocado", "zucchini", "cilantro", "frozen vegetables", "olive", "asparagus", "cabbage", "cauliflower", "dill", "kale", "mixed vegetable", "pumpkin", "squash", "mint", "scallion", "sun dried tomato", "shallot", "eggplant", "beetroot", "butternut squash", "horseradish", "leek", "caper", "brussels sprout", "artichoke heart", "chia seeds", "radish", "sauerkraut", "artichoke", "portobello mushrooms", "weet pepper", "arugula", "spaghetti squash", "capsicum", "bok choy", "parsnip", "okra", "yam", "fennel", "turnip", "snow peas", "bean sprouts", "seaweed", "chard", "collard", "canned tomato", "pimiento", "watercress", "tomatillo", "rocket", "mustard greens", "bamboo shoot", "rutabaga", "endive", "broccoli rabe", "jicama", "kohlrabi", "hearts of palm", "butternut", "celery root", "daikon", "radicchio", "porcini", "chinese broccoli", "jerusalem artichoke", "cresswater chestnut", "dulsemicro greens", "burdock", "chayote"],
                    "Fruit": ["lemon", "apple", "banana", "lime", "strawberry", "orange", "pineapple", "blueberry", "raisin", "coconut", "grape", "peach", "raspberry", "cranberry", "mango", "pear", "blackberry", "cherry", "date", "watermelon", "berries", "kiwi", "grapefruit", "mandarin", "craisins", "cantaloupe", "plum", "apricot", "clementine", "prunes", "apple butter", "pomegranate", "nectarine", "fig", "tangerine", "papaya", "rhubarb", "sultanas", "plantain", "currant", "passion fruit", "guava", "persimmons", "lychee", "lingonberry", "tangelos", "kumquat", "boysenberry", "star fruit", "quince", "honeydew", "crabapples"],
                    "Baking": ["rice", "pasta", "flour", "bread", "baking powder", "baking soda", "bread crumbs", "cornstarch", "rolled oats", "noodle", "flour tortillas", "pancake mix", "yeast", "cracker", "quinoa", "brown rice", "cornmeal", "self raising flour", "cake mix", "saltines", "popcorn", "macaroni cheese mix", "corn tortillas", "ramen", "cereal", "biscuits", "stuffing mix", "couscous", "pie crust", "bisquick", "chips", "angel hair", "coconut flake", "bread flour", "croutons", "lasagne", "pizza dough", "bagel", "puff pastry", "hot dog bun", "barley", "multigrain bread", "potato flakes", "pretzel", "cornbread", "english muffin", "cornflour", "crescent roll dough", "cream of wheat", "coconut flour", "pita", "risotto", "muffin mix", "bicarbonate of soda", "ravioli", "wheat", "rice flour", "polenta", "baguette", "gnocchi", "vermicelli", "semolina", "wheat germ", "buckwheat", "croissants", "bread dough", "filo dough", "yeast flake", "pierogi", "matzo meal", "rye", "tapioca flour", "shortcrust pastry", "potato starch", "breadsticks", "ciabatta", "spelt", "angel food", "tapioca starch", "starch", "whole wheat flour", "gram flour", "sourdough starter", "wafer", "bran", "challah", "sponge cake", "malt extract", "sorghum flour"],
                    "Sweeteners": ["granulated sugar", "brown sugar", "caster sugar", "honey", "confectioners sugar", "maple syrup", "golden syrup", "corn syrup", "molasses", "artificial sweetener", "agave nectar"],
                    "Spices": ["cinnamon", "vanilla extract", "vanilla powder", "garlic powder", "paprika", "smoked paprika", "oregano", "chili powder", "red pepper flake", "cumin", "cayenne", "italian seasoning", "thyme", "onion powder", "nutmeg", "ground nutmeg", "curry powder", "bay leaf", "taco seasoning", "sage", "clove", "allspice", "turmeric", "chive", "pepper", "corn", "ground coriander", "cajun seasoning", "coriander", "celery salt", "herbs", "steak seasoning", "poultry seasoning", "chile powder", "cardamom", "italian herbs", "tarragon", "garam masala", "marjoram", "mustard seed", "celery seed", "chinese five spice", "italian spice", "saffron", "onion flake", "herbes de provence", "chipotle", "dill seed", "fennel seed", "caraway", "cacao", "star anise", "savory", "chili paste", "tamarind", "aniseed", "fenugreek", "lavender", "old bay seasoning", "lemon balm"],
                    "Meats": ["chicken breast", "ground beef", "bacon", "sausage", "beef steak", "ham", "hot dog", "pork chops", "chicken thighs", "ground turkey", "cooked chicken", "turkey", "pork", "pepperoni", "whole chicken", "chicken leg", "ground pork", "chorizo", "chicken wings", "beef roast", "polish sausage", "salami", "pork roast", "ground chicken", "pork ribs", "spam", "venison", "pork shoulder", "bologna", "bratwurst", "prosciutto", "lamb", "corned beef", "chicken roast", "lamb chops", "pancetta", "ground lamb", "beef ribs", "duck", "pork belly", "beef liver", "leg of lamb", "canadian bacon", "beef shank", "veal", "chicken giblets", "cornish hen", "lamb shoulder", "lamb shank", "deer", "ground veal", "pastrami", "rabbit", "sliced turkey", "pork loin", "elk", "beef suet", "veal cutlet", "lamb loin", "marrow bones", "goose", "chicken tenders", "veal chops", "quail", "oxtail", "pheasant", "lamb liver", "moose", "turkey liver", "pork liver", "veal shank", "foie gras", "beef sirloin", "liver sausage", "sweetbread", "wild boar", "snail", "pigeon", "duck liver", "goose liver", "grouse", "ostrich", "soppressata", "alligator"],
                    "Fish": ["canned tuna", "salmon", "tilapia", "fish fillets", "cod", "canned salmon", "anchovy", "smoked salmon", "sardines", "tuna steak", "whitefish", "halibut", "trout", "haddock", "flounder", "catfish", "mahi mahi", "mackerel", "sole", "sea bass", "red snapper", "swordfish", "pollock", "herring", "perch", "grouper", "caviar", "monkfish", "rockfish", "lemon sole", "pike", "barramundi", "eel", "bluefish", "carp", "cuttlefish", "pompano", "arctic char", "john dory", "marlin", "amberjack", "sturgeon"],
                    "Seafood": ["shrimp", "crab", "prawns", "scallop", "clam", "lobster", "mussel", "oyster", "squid", "calamari", "crawfish", "octopus", "cockle", "conch", "sea urchin"],
                    "Condiments": ["mayonnaise", "ketchup", "mustard", "vinegar", "soy sauce", "balsamic vinegar", "worcestershire", "hot sauce", "barbecue sauce", "ranch dressing", "wine vinegar", "apple cider vinegar", "cider vinegar", "italian dressing", "rice vinegar", "salad dressing", "tabasco", "fish sauce", "teriyaki", "steak sauce", "tahini", "enchilada sauce", "vinaigrette dressing", "oyster sauce", "honey mustard", "sriracha", "caesar dressing", "taco sauce", "mirin", "blue cheese dressing", "sweet and sour sauce", "thousand island", "picante sauce", "buffalo sauce", "french dressing", "tartar sauce", "cocktail sauce", "marsala", "adobo sauce", "tzatziki sauce", "sesame dressing", "ponzu", "duck sauce", "pickapeppa sauce", "yuzu juice", "cream sauce"],
                    "Oils": ["olive oil", "vegetable oil", "cooking spray", "canola oil", "shortening", "sesame oil", "coconut oil", "peanut oil", "sunflower oil", "lard", "grape seed oil", "corn oil", "almond oil", "avocado oil", "safflower oil", "walnut oil", "hazelnut oil", "palm oil", "soybean oil", "mustard oil", "pistachio oil", "soya oil"],
                    "Seasonings": ["bouillon", "ground ginger", "sesame seed", "cream of tartar", "chili sauce", "soya sauce", "apple cider", "hoisin sauce", "liquid smoke", "rice wine", "vegetable bouillon", "poppy seed", "balsamic glaze", "miso", "wasabi", "fish stock", "rose water", "pickling salt", "champagne vinegar", "bbq rub", "jamaican jerk spice", "accent seasoning", "pickling spice", "mustard powder", "mango powder", "adobo seasoning", "kasuri methi", "caribbean jerk seasoning", "brine", "matcha powder", "cassia"],
                    "Sauces": ["tomato sauce", "tomato paste", "salsa", "pesto", "alfredo sauce", "beef gravy", "curry paste", "chicken gravy", "cranberry sauce", "turkey gravy", "mushroom gravy", "sausage gravy", "onion gravy", "cream gravy", "pork gravy", "tomato gravy", "giblet gravy"],
                    "Legumes": ["green beans", "peas", "black beans", "chickpea", "lentil", "refried beans", "hummus", "chili beans", "lima beans", "kidney beans", "pinto beans", "edamame", "split peas", "snap peas", "soybeans", "cannellini beans", "navy beans", "french beans", "red beans", "great northern beans", "fava beans"],
                    "Alcohol": ["white wine", "beer", "red wine", "vodka", "rum", "whiskey", "tequila", "sherry", "bourbon", "cooking wine", "whisky", "liqueur", "brandy", "gin", "kahlua", "irish cream", "triple sec", "champagne", "amaretto", "cabernet sauvignon", "vermouth", "bitters", "maraschino", "sake", "grand marnier", "masala", "dessert wine", "schnapps", "port wine", "sparkling wine", "cognac", "chocolate liqueur", "burgundy wine", "limoncello", "creme de menthe", "bloody mary", "raspberry liquor", "curacao", "frangelico", "shaoxing wine", "absinthe", "madeira wine", "ouzo", "anisette", "grappa", "ciclon", "drambuie"],
                    "Soup": ["chicken broth", "mushroom soup", "beef broth", "tomato soup", "vegetable stock", "chicken soup", "onion soup", "vegetable soup", "celery soup", "dashi", "lamb stock", "pork stock", "veal stock"],
                    "Nuts": ["peanut butter", "almond", "walnut", "pecan", "peanut", "cashew", "flax", "pine nut", "pistachio", "almond meal", "hazelnut", "macadamia", "almond paste", "chestnut", "praline", "macaroon"],
                    "Dairy_Alternatives": ["coconut milk", "almond milk", "soy milk", "rice milk", "hemp milk", "non dairy creamer"],
                    "Desserts": ["chocolate", "apple sauce", "strawberry jam", "graham cracker", "marshmallow", "chocolate syrup", "potato chips", "nutella", "chocolate morsels", "bittersweet chocolate", "pudding mix", "raspberry jam", "dark chocolate", "chocolate chips", "jam", "white chocolate", "brownie mix", "chocolate pudding", "jello", "caramel", "chocolate powder", "candy", "corn chips", "cookies", "apricot jam", "chocolate bar", "cookie dough", "oreo", "doritos", "chocolate cookies", "butterscotch", "blackberry preserves", "blueberry jam", "peach preserves", "cherry jam", "fig jam", "plum jam", "cinnamon roll", "fudge", "cookie crumb", "grape jelly", "chilli jam", "lady fingers", "black pudding", "chocolate wafer", "gummy worms", "biscotti biscuit", "doughnut", "amaretti cookies", "apple jelly", "red pepper jelly", "orange jelly", "jalapeno jelly", "mint jelly", "currant jelly", "lemon jelly", "quince jelly"],
                    "Beverages": ["coffee", "orange juice", "tea", "green tea", "apple juice", "tomato juice", "cola", "chocolate milk", "pineapple juice", "lemonade", "cranberry juice", "espresso", "fruit juice", "ginger ale", "club soda", "grenadine", "margarita mix", "cherry juice"]}

# Fetching Recipes to display on the Homepage.

# Mailer config
EMAIL_TO = 'chefitup@gmail.com'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_API_KEY')

# Message Tags
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
CRISPY_TEMPLATE_PACK= "bootstrap4"

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
SIGNING_BACKEND = 'django_cryptography.core.signing.TimestampSigner'

# Twitter API
TWITTER_API_KEY = 'aEDYW3e1hLpgru4mT2SzEBQdx'
TWITTER_API_KEY_SECRET = 'ubAUAsYQbdO9Fz9BQmOjtPK0TdRF8TsF2QnjRtXZLstgi1H7rA'

TWITTER_ACCESS_KEY = '1263218688955756548-9UJJwyJhJ8r7yZLzWNR2d1btSJhKq4'
TWITTER_ACCESS_KEY_SECRET = 'b8yQe6DrTaC0oA66O0TEDxqZYtPPJJTgXqSozMWNZNEVg'

twitter_auth = tweepy.OAuthHandler(TWITTER_API_KEY, TWITTER_API_KEY_SECRET)
twitter_auth.set_access_token(TWITTER_ACCESS_KEY, TWITTER_ACCESS_KEY_SECRET)
TWITTER_API = tweepy.API(twitter_auth)

# Collecting tweets
tweet_status_object = []

TWEET_LIST = []